Q1. Write a program to distinguish between Array Indexing and Fancy Indexing.

In [1]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Array Indexing
print("Array Indexing:")
print(arr[0][1])

# Fancy Indexing
print("Fancy Indexing:")
print(arr[[0, 2], [1, 2]]) 

Array Indexing:
2
Fancy Indexing:
[2 9]


Q2. Execute the 2D array Slicing.

In [2]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing
print("Slicing:")
print(arr[0:2, 1:3]) 


Slicing:
[[2 3]
 [5 6]]


Q3. Create the 5-Dimensional arrays using ‘ndmin’.

In [3]:
import numpy as np

# Create a 5-dimensional array
arr = np.array([1, 2, 3, 4], ndmin=5)

print("The created array is:")
print(arr)
print("The number of dimensions of the array is:", arr.ndim)

The created array is:
[[[[[1 2 3 4]]]]]
The number of dimensions of the array is: 5


Q4. Reshape the array from 1-D to 2-D array.

In [4]:
import numpy as np

# Create a 1-D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2-D array
new_arr = arr.reshape(2, 3)

print("Original array:")
print(arr)

print("Reshaped array:")
print(new_arr)


Original array:
[1 2 3 4 5 6]
Reshaped array:
[[1 2 3]
 [4 5 6]]


Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [5]:
import numpy as np

# Create two 2D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Stack the arrays using different functions
print("Stack():")
print(np.stack((a, b), axis=0))

print("hstack():")
print(np.hstack((a, b)))

print("vstack():")
print(np.vstack((a, b)))

print("dstack():")
print(np.dstack((a, b)))

Stack():
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
hstack():
[[1 2 5 6]
 [3 4 7 8]]
vstack():
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
dstack():
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


Q6. Perform the searchsort method in Numpy array.


In [6]:
import numpy as np

# Create an input array
arr = np.array([2, 3, 4, 5, 6])

# Find the indices to maintain sorted array
out_ind = np.searchsorted(arr, 4)

print("Output indices to maintain sorted array:", out_ind)

Output indices to maintain sorted array: 2


Q7. Create Numpy Structured array using your domain features.

In [11]:
import numpy as np

# Define the data types for the fields
dt = np.dtype([('name', 'U20'), ('model', 'U20'), ('price', 'f4'), ('year', 'i4'), ('color', 'U20')])

# Create a structured array
arr = np.array([('himalayan', 'Mountain', 500.0, 2021, 'Red'), ('royal enfield', 'Road', 800.0, 2022, 'Blue')], dtype=dt)

print("The created structured array is:")
print(arr)


The created structured array is:
[('himalayan', 'Mountain', 500., 2021, 'Red')
 ('royal enfield', 'Road', 800., 2022, 'Blue')]


Q8. Create Data frame using List and Dictionary.

In [15]:
import pandas as pd

# Define the data as a list of dictionaries
data = [
    {'name': 'himalayan', 'model': 'Mountain',  'price':150000.0,},
    {'name': 'royal enfield', 'model': 'Road',  'price':60000.0,},
    {'name': 'avengers', 'model': 'Hybrid',  'price':500000.0,},
    {'name': 'NS200', 'model': 'BMX',  'price':450000.0,},
]

# Create a DataFrame from the data
df = pd.DataFrame(data)

print("The created DataFrame is:")
print(df)

The created DataFrame is:
            name     model     price
0      himalayan  Mountain  150000.0
1  royal enfield      Road   60000.0
2       avengers    Hybrid  500000.0
3          NS200       BMX  450000.0


Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()

In [1]:

import pandas as pd
import numpy as np

# Create a dictionary with bike data
bike_data = {
    'name': ['himalayan', 'royal enfield', 'avengers', 'NS200', 'omega'],
    'model': ['Mountain', 'Road', 'Hybrid', 'BMX', 'Electric'],
    'price': [500.0, 800.0, np.nan, 600.0, 1200.0],
    'year': [2021, 2022, 2023, np.nan, 2024],
    'color': ['Red', 'Blue', np.nan, 'Green', 'Black']
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(bike_data)

# Check for missing data
print("Missing data:\n", df.isnull())

# Check for non-missing data
print("Non-missing data:\n", df.notnull())

# Drop rows with missing data
df.dropna(inplace=True)
print("After dropping rows with missing data:\n", df)

# Fill missing values with a specific value
df.fillna(0, inplace=True)
print("After filling missing values with zero:\n", df)

# Replace missing values with the mean of the column
df['price'].replace(np.nan, df['price'].mean(), inplace=True)
print("After replacing missing values with the mean of the column:\n", df)

# Interpolate missing values
df.interpolate(inplace=True)
print("After interpolating missing values:\n", df)

Missing data:
     name  model  price   year  color
0  False  False  False  False  False
1  False  False  False  False  False
2  False  False   True  False   True
3  False  False  False   True  False
4  False  False  False  False  False
Non-missing data:
    name  model  price   year  color
0  True   True   True   True   True
1  True   True   True   True   True
2  True   True  False   True  False
3  True   True   True  False   True
4  True   True   True   True   True
After dropping rows with missing data:
             name     model   price    year  color
0      himalayan  Mountain   500.0  2021.0    Red
1  royal enfield      Road   800.0  2022.0   Blue
4          omega  Electric  1200.0  2024.0  Black
After filling missing values with zero:
             name     model   price    year  color
0      himalayan  Mountain   500.0  2021.0    Red
1  royal enfield      Road   800.0  2022.0   Blue
4          omega  Electric  1200.0  2024.0  Black
After replacing missing values with the mean of

/var/folders/6y/g5m9s7tn5dbgx88kjx9hxys00000gn/T/ipykernel_7468/3208745356.py:35: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(inplace=True)


Q10. Perform the Hierarchical Indexing in the above created dataset.

In [14]:
import pandas as pd

# Create a dictionary with bike data
bike_data = {
    'name': ['himalayan', 'royal enfield', 'avengers', 'NS200', 'omega'],
    'model': ['Mountain', 'Road', 'Hybrid', 'BMX', 'Electric'],
    'price': [500.0, 800.0, 600.0, 700.0, 1200.0],
    'year': [2021, 2022, 2023, 2024, 2025],
    'color': ['Red', 'Blue', 'Green', 'Yellow', 'Black']
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(bike_data)

# Set the index to be the name and model columns
df.set_index(['name', 'model'], inplace=True)

print("The created DataFrame with hierarchical index is:")
print(df)


The created DataFrame with hierarchical index is:
                         price  year   color
name          model                         
himalayan     Mountain   500.0  2021     Red
royal enfield Road       800.0  2022    Blue
avengers      Hybrid     600.0  2023   Green
NS200         BMX        700.0  2024  Yellow
omega         Electric  1200.0  2025   Black
